test-live-site:
    runs-on: ubuntu-latest
    needs: deploy 
    steps:
      - uses: actions/checkout@v4
      - name: Lighthouse Live Audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://website.com/
            https://website.com/blogs/1
          uploadArtifacts: true
          temporaryPublicStorage: true